---
# handlers file for dfirtrack

- name: NGINX | Restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
  become_method: sudo

- name: POSTGRESQL | Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
  become: yes
  become_method: sudo
